# ==============================================================================
#  VCLite Citrix Billing Report — Configuration File
#  Filename : VCLite_BillingReport.ini
#  Location : Same folder as VCLite_BillingReport.ps1
#
#  Generated output HTML is saved to:
#    <ScriptFolder>\output\VCLite_BillingReport_YYYYMMDD_HHmmss.html
#
#  Lines beginning with # are comments and are ignored.
#  DO NOT commit this file to source control.
# ==============================================================================

[CitrixCloud]
# Citrix Cloud Customer ID  (Citrix Cloud > Identity & Access > API Access)
CustomerId   = ewy3n89x3jns

# API Client ID (GUID)
ClientId     = ba3e7acc-79b1-41ad-835c-90f10f4dd185

# API Client Secret (plain text)
ClientSecret = a6P_9bHH2ADWbWF5VCf0TQ==

[API]
# OAuth2 token endpoint (change -us to -eu or -ap for other regions)
TrustUrl   = https://api-us.cloud.com/cctrustoauth2

# Citrix Monitor OData endpoint
MonitorUrl = https://api-us.cloud.com/monitorodata

[Output]
# Root folder where this PS1 and HTML template reside.
# The script automatically creates an "output" subfolder here.
# Generated HTML files are saved to:  <ScriptFolder>\output\
ScriptFolder = C:\Scripts\VCLite
