name: 'Terraform'

on: [push, pull_request]

env:
  TF_LOG: INFO

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./  # <-- change if your Terraform files are in a folder

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.0.10

      # 3️⃣ Cache Terraform plugins/modules
      - name: Cache Terraform modules
        uses: actions/cache@v3
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf*') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      # 4️⃣ Debug: list files to check path
      - name: List directory
        run: ls -R

      # 5️⃣ Terraform Init
      - name: Terraform Init
        id: init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
          RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
          STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
          CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
        run: |
          terraform init \
            -backend-config="storage_account_name=$STORAGE_ACCOUNT" \
            -backend-config="container_name=$CONTAINER_NAME" \
            -backend-config="resource_group_name=$RESOURCE_GROUP" \
            -backend-config="key=terraform.tfstate"

      # 6️⃣ Terraform Validate
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      # 7️⃣ Terraform Plan (for PRs only)
      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        env:
          ARM_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
        run: |
          terraform plan -no-color -out=tfplan | tee plan.txt
          echo "plan_output<<EOF" >> $GITHUB_OUTPUT
          cat plan.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # 8️⃣ Add Plan Comment to PR
      - name: Add Plan Comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.AZ_GIT_TOKEN }}
          script: |
            const plan = `${{ steps.plan.outputs.plan_output }}`;
            const commentBody = `
            #### Terraform Init: \`${{ steps.init.outcome }}\`
            #### Terraform Validate: \`${{ steps.validate.outcome }}\`
            #### Terraform Plan: \`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>
            \`\`\`
            ${plan}
            \`\`\`
            </details>

            *Triggered by: @${{ github.actor }}, Workflow: \`${{ github.workflow }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });

      # 9️⃣ Terraform Apply (only on main branch)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          ARM_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
        run: terraform apply -auto-approve -input=false
